export const DefaultConfigs: {
    key: string
    value: string
    description?: string
}[] = [
    {
        key: "llm.models",
        value: JSON.stringify([
            "gpt-5.2",
            "gpt-5.1",
            "gpt-5",
            "gpt-5-mini",
            "gpt-5-nano",
            "gpt-5.2-chat-latest",
            "gpt-5.1-chat-latest",
            "gpt-5-chat-latest",
            "gpt-5.2-codex",
            "gpt-5.1-codex-max",
            "gpt-5.1-codex",
            "gpt-5-codex",
            "gpt-5.2-pro",
            "gpt-5-pro",
            "gpt-4.1",
            "gpt-4.1-mini",
            "gpt-4.1-nano",
            "gpt-4o",
            "gpt-4o-2024-05-13",
            "gpt-4o-mini",
        ]),
        description: "Available global LLM model candidates shown in selectors (JSON array).",
    },
    {
        key: "search.intent_resolve.model",
        value: "gpt-5-mini",
        description: "LLM model used for search intent resolution.",
    },
    {
        key: "search.content_generation.model",
        value: "gpt-5.2-chat-latest",
        description: "LLM model used for search content/article generation.",
    },
    {
        key: "search.spelling_correction.model",
        value: "gpt-5-mini",
        description: "LLM model used for search spelling correction.",
    },
    {
        key: "search.spell_correction_mode",
        value: "auto",
        description: "Spell correction mode for search query normalization: off|auto|force.",
    },
    {
        key: "llm.baseurl",
        value: "",
        description: "Optional OpenAI-compatible base URL used by LLM calls. Leave empty for default OpenAI endpoint.",
    },
    {
        key: "search.example_queries",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "rag architecture",
            "node express memory leak",
            "typescript api error handling",
            "self hosted vector database",
            "llm system prompt template",
        ]),
        description: "Example queries shown on the search home screen for first-time users (JSON array).",
    },
    {
        key: "search.example_queries.zh-cn",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "rag 架构",
            "node express 内存泄漏",
            "typescript api 错误处理",
            "自托管 向量数据库",
            "llm system prompt 模板",
        ]),
        description: "Localized example queries for Simplified Chinese users (JSON array).",
    },
    {
        key: "search.example_queries.zh-tw",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "rag 架構",
            "node express 記憶體洩漏",
            "typescript api 錯誤處理",
            "自託管 向量資料庫",
            "llm system prompt 範本",
        ]),
        description: "Localized example queries for Traditional Chinese users (JSON array).",
    },
    {
        key: "search.example_queries.ja",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "rag アーキテクチャ",
            "node express メモリリーク",
            "typescript api エラーハンドリング",
            "セルフホスト ベクタdb",
            "llm システムプロンプト テンプレート",
        ]),
        description: "Localized example queries for Japanese users (JSON array).",
    },
    {
        key: "search.example_queries.ko",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "rag 아키텍처",
            "node express 메모리 누수",
            "typescript api 에러 처리",
            "셀프호스팅 벡터 db",
            "llm 시스템 프롬프트 템플릿",
        ]),
        description: "Localized example queries for Korean users (JSON array).",
    },
    {
        key: "search.example_queries.es",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "arquitectura rag",
            "node express memory leak",
            "typescript api manejo de errores",
            "base de datos vectorial self hosted",
            "llm system prompt plantilla",
        ]),
        description: "Localized example queries for Spanish users (JSON array).",
    },
    {
        key: "search.example_queries.fr",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "architecture rag",
            "node express memory leak",
            "typescript api gestion erreurs",
            "base de donnees vectorielle self hosted",
            "llm system prompt modele",
        ]),
        description: "Localized example queries for French users (JSON array).",
    },
    {
        key: "search.example_queries.de",
        value: JSON.stringify([
            "sqlite fts5 bm25",
            "rag architektur",
            "node express memory leak",
            "typescript api fehlerbehandlung",
            "self hosted vektor datenbank",
            "llm system prompt vorlage",
        ]),
        description: "Localized example queries for German users (JSON array).",
    },
    {
        key: "search.recent.min_query_chars",
        value: "3",
        description: "Minimum query length required for storing search history.",
    },
    {
        key: "search.recent.dedupe_window_seconds",
        value: "300",
        description: "Skip recording duplicate recent queries within this time window (in seconds).",
    },
    {
        key: "search.recent.blacklist_terms",
        value: JSON.stringify(["test", "testing", "asdf", "qwer", "zxcv", "1234"]),
        description: "Exact query terms excluded from recent history chips (JSON array, case-insensitive).",
    },
    {
        key: "llm.apikey.env_name",
        value: "OPENAI_API_KEY",
        description: "Environment variable name used to read API key for LLM calls.",
    },
    {
        key: "llm.retry.max_attempts",
        value: "2",
        description: "Maximum attempts for LLM generation calls before giving up.",
    },
    {
        key: "llm.retry.timeout_ms",
        value: "20000",
        description: "Per-attempt timeout in milliseconds for LLM generation calls.",
    },
]
