export const DefaultConfigs: {
    key: string
    value: string
    description?: string
}[] = [
    {
        key: "llm.models",
        value: JSON.stringify([
            "gpt-5.2",
            "gpt-5.1",
            "gpt-5",
            "gpt-5-mini",
            "gpt-5-nano",
            "gpt-5.2-chat-latest",
            "gpt-5.1-chat-latest",
            "gpt-5-chat-latest",
            "gpt-5.2-codex",
            "gpt-5.1-codex-max",
            "gpt-5.1-codex",
            "gpt-5-codex",
            "gpt-5.2-pro",
            "gpt-5-pro",
            "gpt-4.1",
            "gpt-4.1-mini",
            "gpt-4.1-nano",
            "gpt-4o",
            "gpt-4o-2024-05-13",
            "gpt-4o-mini",
        ]),
        description: "Available global LLM model candidates shown in selectors (JSON array).",
    },
    {
        key: "search.intent_resolve.model",
        value: "gpt-5-mini",
        description: "LLM model used for search intent resolution.",
    },
    {
        key: "search.content_generation.model",
        value: "gpt-5.2-chat-latest",
        description: "LLM model used for search content/article generation.",
    },
    {
        key: "search.spelling_correction.model",
        value: "gpt-5-mini",
        description: "LLM model used for search spelling correction.",
    },
    {
        key: "search.spell_correction_mode",
        value: "auto",
        description: "Spell correction mode for search query normalization: off|auto|force.",
    },
    {
        key: "llm.baseurl",
        value: "",
        description: "Optional OpenAI-compatible base URL used by LLM calls. Leave empty for default OpenAI endpoint.",
    },
    {
        key: "search.example_queries",
        value: JSON.stringify([
            "laplace transform table",
            "schrodinger equation intuition",
            "database indexing strategy",
            "sqlite fts5 bm25",
            "ubuntu install ohmyzsh",
            "rag chunking strategy",
            "causes of world war i",
            "insulin resistance basics",
        ]),
        description: "Example queries shown on the search home screen for first-time users (JSON array).",
    },
    {
        key: "search.example_queries.zh-cn",
        value: JSON.stringify([
            "拉普拉斯变换 表",
            "薛定谔方程 直观理解",
            "数据库 索引 策略",
            "sqlite fts5 bm25",
            "ubuntu 安装 ohmyzsh",
            "rag 分块 策略",
            "第一次世界大战 起因",
            "胰岛素抵抗 基础概念",
        ]),
        description: "Localized example queries for Simplified Chinese users (JSON array).",
    },
    {
        key: "search.example_queries.zh-tw",
        value: JSON.stringify([
            "拉普拉斯轉換 表",
            "薛丁格方程 直覺理解",
            "資料庫 索引 策略",
            "sqlite fts5 bm25",
            "ubuntu 安裝 ohmyzsh",
            "rag 分塊 策略",
            "第一次世界大戰 起因",
            "胰島素阻抗 基礎概念",
        ]),
        description: "Localized example queries for Traditional Chinese users (JSON array).",
    },
    {
        key: "search.example_queries.ja",
        value: JSON.stringify([
            "ラプラス変換 表",
            "シュレディンガー方程式 直感",
            "データベース インデックス 戦略",
            "sqlite fts5 bm25",
            "ubuntu ohmyzsh インストール",
            "rag チャンク分割 戦略",
            "第一次世界大戦 原因",
            "インスリン抵抗性 基礎",
        ]),
        description: "Localized example queries for Japanese users (JSON array).",
    },
    {
        key: "search.example_queries.ko",
        value: JSON.stringify([
            "라플라스 변환 표",
            "슈뢰딩거 방정식 직관",
            "데이터베이스 인덱싱 전략",
            "sqlite fts5 bm25",
            "ubuntu ohmyzsh 설치",
            "rag 청크 전략",
            "1차 세계대전 원인",
            "인슐린 저항성 기초",
        ]),
        description: "Localized example queries for Korean users (JSON array).",
    },
    {
        key: "search.example_queries.es",
        value: JSON.stringify([
            "tabla transformada de laplace",
            "intuicion ecuacion de schrodinger",
            "estrategia de indexacion base de datos",
            "sqlite fts5 bm25",
            "ubuntu instalar ohmyzsh",
            "estrategia de chunking rag",
            "causas de la primera guerra mundial",
            "resistencia a la insulina conceptos basicos",
        ]),
        description: "Localized example queries for Spanish users (JSON array).",
    },
    {
        key: "search.example_queries.fr",
        value: JSON.stringify([
            "table de transformee de laplace",
            "intuition equation de schrodinger",
            "strategie d indexation base de donnees",
            "sqlite fts5 bm25",
            "ubuntu installer ohmyzsh",
            "strategie de chunking rag",
            "causes de la premiere guerre mondiale",
            "resistance a l insuline notions de base",
        ]),
        description: "Localized example queries for French users (JSON array).",
    },
    {
        key: "search.example_queries.de",
        value: JSON.stringify([
            "laplace transformation tabelle",
            "schrodinger gleichung intuition",
            "datenbank indexierungsstrategie",
            "sqlite fts5 bm25",
            "ubuntu ohmyzsh installieren",
            "rag chunking strategie",
            "ursachen erster weltkrieg",
            "insulinresistenz grundlagen",
        ]),
        description: "Localized example queries for German users (JSON array).",
    },
    {
        key: "search.recent.min_query_chars",
        value: "3",
        description: "Minimum query length required for storing search history.",
    },
    {
        key: "search.recent.dedupe_window_seconds",
        value: "300",
        description: "Skip recording duplicate recent queries within this time window (in seconds).",
    },
    {
        key: "search.recent.blacklist_terms",
        value: JSON.stringify(["test", "testing", "asdf", "qwer", "zxcv", "1234"]),
        description: "Exact query terms excluded from recent history chips (JSON array, case-insensitive).",
    },
    {
        key: "llm.apikey.env_name",
        value: "OPENAI_API_KEY",
        description: "Environment variable name used to read API key for LLM calls.",
    },
    {
        key: "llm.retry.max_attempts",
        value: "2",
        description: "Maximum attempts for LLM generation calls before giving up.",
    },
    {
        key: "llm.retry.timeout_ms",
        value: "40000",
        description: "Per-attempt timeout in milliseconds for LLM generation calls.",
    },
]
